### ISSUE TITLE
Nlog does not work

### ISSUE THREAD

**Issue by weedkiller** [gus-sosa/FileWatcher#10]
Hi, I cant get Nlog to show me the output no the console or server.

I can see top shelf messages till the service comes up in the console, but the logger messages are missing `.\logs\` is missing in both `bin\debug\` and for rel. builds in  `bin\release` 

Can you please tell me how to locate this or configure it to a simple base path under `C:\logs` i.e. something simple, by removing AppDomain. on Windows 10 but it still does not show up there.

**Comment by gus-sosa** [comment]
I believe the folder logs must be in`.\`. Then if it is not there, just create it. After that logs should come into the folder.

Also, there are internal logs of NLogs in `c:\temp\nlog-internal.log`.

Also, there is a background process to remove logs after a time, keep that in mind.

**Comment by weedkiller** [comment]
Yes, thanks for pointing out the remove logs, I have commented that out for now.

"_I believe the folder logs must be in.\_" can you give me a example, which path is this relative to, i.e. is it relative to target bin debug folders? I dont see anything there.

I have made some minor updates to check for a folder and create it if it does not exist, which works in creating the folder, but the log files are still not getting logged/there.
