### ISSUE TITLE
Access Denied when trying to access the path

### ISSUE THREAD

**Issue by weedkiller** [gus-sosa/FileWatcher#9]
Hello, this is very nice, I am trying to use your file watcher to try out, but I keep getting access denied on the folder. I searched, changed permissions on the folder but i still get the same error. Below is the exception.

1. Also can you please tell me where is the `.\logs` directory and files I cant find it in bin or debug?
2. Exception = `e = {"Access to the path 'C:\\eLearning\\bin\\Debug\\1_CSV' is denied."}`

![image](https://user-images.githubusercontent.com/21086190/50381831-bbdc9a00-065e-11e9-8f76-53340293d54f.png)

thanks

**Comment by weedkiller** [comment]
hello @gus-sosa , first this a very nice lib good work 👍 

Ok, the problem was the `filestream` code, not sure, but it seemed like you are trying to stream a Dir and that would work, please double if thats possible. When I changed that worked.


1. The Logs folder is not in the `Bin\Debug` (build output), I also tried to get rid of the APP.Domain... and do it directly to `C:\Logs\` that didnt work either.  
2. I was trying to share an update to get it working on current version of Hangfire, that configuration also changed with latest version.

**Comment by gus-sosa** [comment]
This is happening to you because it is looking for the file folders.config, which I assume was not in your output project.

I believe you have to create that file and just add a line with the path of a folder to watch.

Let me know if that works.

**Comment by gus-sosa** [comment]
For the logs. Just create the folder logs by yourself. Then you might be able to see the logs coming.

**Comment by weedkiller** [comment]
Hi, `folders.config` is a variable for whatever output folder we choose, correct? I'm able to verify that its creating that folder from folders.config.

It would be nice to have a base folder option. For e.g. if its running in production sometimes they just want it right under `D:/<YourFoldersHere>` for e.g `D:/Logs` so that its available to splunk or elastic/graphana
